In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

print(Path.cwd())

/Users/samuelmacedo/Projetos/Pandas/notebooks

In [2]:
df_vendas = pd.read_csv("../datasets/vendas_tech.csv", low_memory=False)
display(df_vendas)

df_gerentes = pd.read_excel('../datasets/gerentes_lojas.xlsx')
display(df_gerentes)

display(df_vendas.info())
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [3]:
df_analysis = df_vendas.drop(columns=['Data_Base'])

df_analysis["Loja"] = df_analysis["Loja"].fillna("Online")

df_analysis["Data"] = pd.to_datetime(df_analysis["Data"], format='%Y-%m-%d')

df_analysis["Loja"] = df_analysis["Loja"].str.strip()
df_analysis["Loja"] = df_analysis["Loja"].str.title()

df_analysis = df_analysis.drop_duplicates(subset=["ID_Pedido"])



display(df_analysis.info())
display(df_analysis.columns)
display(df_analysis.head())
display(df_analysis)

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 5.3 MB

None

Index(['ID_Pedido', 'Data', 'Loja', 'Produto', 'Preco_Unitario', 'Qtd',
       'Cliente'],
      dtype='str')

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

In [4]:
df_analysis['Faturamento'] = df_analysis["Preco_Unitario"] * df_analysis["Qtd"]

df_analysis["Forma_de_Venda"] = np.where(
    df_analysis["Loja"]=="Online",
    "Online",
    "Presencial"
)

regions_dict = {
    'São Paulo': 'Sudeste',
    'Belo Horizonte': 'Sudeste',
    'Online': 'Online',
    'Rio De Janeiro': 'Sudeste',
    'Curitiba': 'Sul',
    'Porto Alegre': 'Sul',
    'Recife': 'Nordeste',
    'Salvador': 'Nordeste'
}

df_analysis["Regiao"] = df_analysis["Loja"].map(regions_dict)

display(df_analysis)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial,Sul

In [5]:
# analisar -> filtrar dados

corrigido = df_analysis.sort_values(by='Data')  # -> esta mudando pq existem varias datas do mesmo dia

# .loc[] -> .loc[linha, 'Nome da coluna']
loja = corrigido.loc[3, 'Loja']  
cliente = corrigido.loc[4, 'Cliente']
produto = corrigido.loc[4, 'Produto']

# .iloc -> por posicao (indice, coluna, sem contar coluna de indices) -> .iloc[linha, coluna]
id_pedido = 2
loja_id_2 = corrigido.iloc[2, 2]
cliente_id_2 = corrigido.iloc[2, 6]
produto_id_2 = corrigido.iloc[2, 3]

# condicional: 
df_id_pedido_4 = corrigido[corrigido['ID_Pedido'] == 4]

# exportar as vendas de 2024
df_exportar_vendas_2024 = corrigido[corrigido['Data']=="2024-01-01"]

# exportar pedacos da base: 
df_vendas_sp = corrigido[corrigido["Loja"]=="São Paulo"]
df_vendas_sp.to_csv("Vendas_sp.csv", index=False)

# dupla comdicional
df_vendas_HDMI_SUL = corrigido[
    (corrigido['Produto'] == "Cabo HDMI") &
    (corrigido['Regiao'] == "Sul")
]

display(corrigido)

print(loja, cliente, produto)
print(loja_id_2, cliente_id_2, produto_id_2)

display(df_id_pedido_4)
display(df_exportar_vendas_2024)

display(df_vendas_HDMI_SUL)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
34749,34750,2023-01-01,Rio De Janeiro,Notebook HP,3200.0,1,Cliente_9014,3200.0,Presencial,Sudeste
13698,13699,2023-01-01,Rio De Janeiro,Teclado Mecânico,250.0,1,Cliente_24330,250.0,Presencial,Sudeste
81393,81394,2023-01-01,Porto Alegre,Teclado Mecânico,250.0,1,Cliente_9758,250.0,Presencial,Sul
250,251,2023-01-01,São Paulo,Teclado Mecânico,250.0,3,Cliente_22822,750.0,Presencial,Sudeste
77067,77068,2023-01-01,Rio De Janeiro,Notebook Dell,3500.0,1,Cliente_554,3500.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
43206,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
3182,3183,2024-12-30,Salvador,Mouse Gamer,120.0,1,Cliente_4075,120.0,Presencial,Nordeste
9460,9461,2024-12-30,Porto Alegre,Teclado Mecânico,250.0,1,Cliente_22763,250.0,Presencial,Sul
2792,2793,2024-12-30,Salvador,Notebook Dell,3500.0,1,Cliente_24692,3500.0,Presencial,Nordeste
91692,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,5500.0,Presencial,Sudeste

Rio De Janeiro Cliente_23377 Smartphone Samsung
Porto Alegre Cliente_9758 Teclado Mecânico

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
86877,86878,2024-01-01,Salvador,"Monitor 27""",1200.0,1,Cliente_21318,1200.0,Presencial,Nordeste
65073,65074,2024-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_9100,40.0,Presencial,Sudeste
88698,88699,2024-01-01,Belo Horizonte,"Monitor 27""",1200.0,1,Cliente_16957,1200.0,Presencial,Sudeste
51671,51672,2024-01-01,Porto Alegre,Notebook HP,3200.0,1,Cliente_16437,3200.0,Presencial,Sul
44183,44184,2024-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_1577,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
40651,40652,2024-01-01,Porto Alegre,Smartphone Samsung,2200.0,2,Cliente_29943,4400.0,Presencial,Sul
55296,55297,2024-01-01,Curitiba,Mouse Gamer,120.0,3,Cliente_28080,360.0,Presencial,Sul
83655,83656,2024-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_15422,40.0,Presencial,Nordeste
98398,98399,2024-01-01,Curitiba,Notebook Dell,3500.0,1,Cliente_2701,3500.0,Presencial,Sul
2814,2815,2024-01-01,Recife,iPhone 14,5500.0,2,Cliente_14933,11000.0,Presencial,Nordeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
70137,70138,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_9348,40.0,Presencial,Sul
97658,97659,2023-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_58,40.0,Presencial,Sul
42050,42051,2023-01-01,Curitiba,Cabo HDMI,40.0,10,Cliente_16622,400.0,Presencial,Sul
37129,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,40.0,Presencial,Sul
49139,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
35126,35127,2024-12-30,Curitiba,Cabo HDMI,40.0,2,Cliente_20687,80.0,Presencial,Sul
75694,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,40.0,Presencial,Sul
47773,47774,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_14363,80.0,Presencial,Sul
64472,64473,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_11598,80.0,Presencial,Sul
78583,78584,2024-12-30,Curitiba,Cabo HDMI,40.0,1,Cliente_21307,40.0,Presencial,Sul

In [6]:
# analise por agrupamento: 

# ranking de faturamento por loja: 
analise_lojas = corrigido[["Loja", "Faturamento"]].groupby("Loja").sum()
analise_lojas = analise_lojas.sort_values(by="Faturamento", ascending=False)
analise_lojas = analise_lojas.reset_index()  # -> faz os indices voltarem
analise_lojas["Faturamento"] = analise_lojas["Faturamento"].map("RS: {:,.2f}".format)

# ranking de produtos que mais venderam online
vendas_online = corrigido[corrigido["Loja"]=="Online"]
online = vendas_online[["Faturamento", "Qtd"]].groupby("Faturamento").sum()
online = online.sort_values(by="Qtd", ascending=False)
online = online.rename(columns={"Qtd": "Vendas Totais"})

# quais produtos venderam mais em cada uma das lojas:
analise_mais_vendidos = corrigido[["Loja", "Produto", "Qtd"]].groupby(["Loja", "Produto"]).sum()

display(analise_lojas)
display(online)
display(analise_mais_vendidos)

             Loja        Faturamento
0        Salvador  RS: 42,300,610.00
1  Rio De Janeiro  RS: 42,294,720.00
2          Recife  RS: 42,190,390.00
3       São Paulo  RS: 42,090,690.00
4  Belo Horizonte  RS: 41,714,890.00
5    Porto Alegre  RS: 41,678,460.00
6        Curitiba  RS: 41,121,720.00
7          Online   RS: 6,080,850.00

             Vendas Totais
Faturamento
120.0                  240
5500.0                 207
3200.0                 206
40.0                   201
3500.0                 186
2200.0                 184
1200.0                 180
250.0                  173
11000.0                119
6400.0                  88
80.0                    82
240.0                   76
500.0                   74
2400.0                  74
10500.0                 60
16000.0                 60
7000.0                  58
27500.0                 55
600.0                   50
360.0                   48
9600.0                  48
200.0                   45
4400.0                  44
32000.0                 40
55000.0                 40
1250.0                  40
750.0                   36
6000.0                  35
17500.0                 35
3600.0                  33
400.0                   30
35000.0                 30
16500.0                 24
2500.0                  20
12000.0                 20
6600.0                  18
22000.0                 10

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
...                                 ...
São Paulo      Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado Mecânico    2589
               iPhone 14           2735

[64 rows x 1 columns]