In [1]:
import pandas as pd

dados = {
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo'],
    # 'Area': ['Administrativo', 'Financeiro', 'Vendas', 'Administrativo', 'Financeiro'],
    'Idade': [25, 30, 35, 40, 45],
    'Salário': [3000, None, 7000, None, 11000]
}

df = pd.DataFrame(dados)

In [2]:
# describe function: 

display(df.describe())

           Idade  Salário
count   5.000000      3.0
mean   35.000000   7000.0
std     7.905694   4000.0
min    25.000000   3000.0
25%    30.000000   5000.0
50%    35.000000   7000.0
75%    40.000000   9000.0
max    45.000000  11000.0

In [3]:
# apply function

df["Salario Ajustado"] = df["Salário"].apply(lambda x: x * 1.1)

display(df)

      Nome  Idade  Salário  Salario Ajustado
0      Ana     25   3000.0            3300.0
1    Bruno     30      NaN               NaN
2   Carlos     35   7000.0            7700.0
3  Daniela     40      NaN               NaN
4  Eduardo     45  11000.0           12100.0

In [4]:
# groupby

# medias_area = df.groupby('Area').mean(numeric_only=True)
# display(medias_area)

In [5]:
# fillna -> preenche valores nulos

media_salarial = df["Salário"].mean(numeric_only=True)
df["Salário"] = df["Salário"].fillna(media_salarial)

df["Salario Ajustado"] = df["Salario Ajustado"].fillna(media_salarial)


display(df)

      Nome  Idade  Salário  Salario Ajustado
0      Ana     25   3000.0            3300.0
1    Bruno     30   7000.0            7000.0
2   Carlos     35   7000.0            7700.0
3  Daniela     40   7000.0            7000.0
4  Eduardo     45  11000.0           12100.0

In [6]:
# merge: mesclar tabelas

tabela_areas = pd.DataFrame({
    "Nome Funcionario": ['Ana', 'Bruno', 'Carlos', 'Eduardo'],
    "Area": ['Administrativo', 'Financeiro', 'Vendas', 'Financeiro']
})

df = df.merge(tabela_areas, how='left', left_on='Nome', right_on='Nome Funcionario')
df = df.drop(columns="Nome Funcionario")

display(df)
display(tabela_areas)

      Nome  Idade  Salário  Salario Ajustado            Area
0      Ana     25   3000.0            3300.0  Administrativo
1    Bruno     30   7000.0            7000.0      Financeiro
2   Carlos     35   7000.0            7700.0          Vendas
3  Daniela     40   7000.0            7000.0             NaN
4  Eduardo     45  11000.0           12100.0      Financeiro

  Nome Funcionario            Area
0              Ana  Administrativo
1            Bruno      Financeiro
2           Carlos          Vendas
3          Eduardo      Financeiro