In [11]:
import pandas as pd
from pathlib import Path

In [12]:
caminho = Path.home() / "Downloads" / "dados_hospedagem.json"

dados = pd.read_json(caminho)

display(dados.head())

                                         info_moveis
0  {'avaliacao_geral': '10.0', 'experiencia_local...
1  {'avaliacao_geral': '10.0', 'experiencia_local...
2  {'avaliacao_geral': '10.0', 'experiencia_local...
3  {'avaliacao_geral': '10.0', 'experiencia_local...
4  {'avaliacao_geral': '10.0', 'experiencia_local...

In [13]:
# dados = pd.json_normalize(dados['info_moveis'])

display(dados.head())

                                         info_moveis
0  {'avaliacao_geral': '10.0', 'experiencia_local...
1  {'avaliacao_geral': '10.0', 'experiencia_local...
2  {'avaliacao_geral': '10.0', 'experiencia_local...
3  {'avaliacao_geral': '10.0', 'experiencia_local...
4  {'avaliacao_geral': '10.0', 'experiencia_local...

In [14]:
colunas = list(dados.columns)

In [15]:
# dados = dados.explode(colunas[3:])
# dados

In [16]:
dados.reset_index(inplace=True, drop=True)
dados.head()

                                         info_moveis
0  {'avaliacao_geral': '10.0', 'experiencia_local...
1  {'avaliacao_geral': '10.0', 'experiencia_local...
2  {'avaliacao_geral': '10.0', 'experiencia_local...
3  {'avaliacao_geral': '10.0', 'experiencia_local...
4  {'avaliacao_geral': '10.0', 'experiencia_local...

In [17]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   info_moveis  70 non-null     object
dtypes: object(1)
memory usage: 692.0+ bytes

In [18]:
import numpy as np

In [19]:
dados['max_hospedes'] = dados['max_hospedes'].astype(np.int64)
display(dados['max_hospedes'])

KeyError: 'max_hospedes'

In [ ]:
colunas_numericas = ["quantidade_banheiros", "quantidade_quartos", "quantidade_camas"]
dados[colunas_numericas] = dados[colunas_numericas].astype(np.int64)

display(dados[colunas_numericas])

      quantidade_banheiros  quantidade_quartos  quantidade_camas
0                        1                   1                 1
1                        1                   1                 1
2                        1                   1                 1
3                        1                   1                 1
4                        1                   1                 1
...                    ...                 ...               ...
3813                     3                   4                 5
3814                     2                   4                 4
3815                     1                   3                 4
3816                     2                   3                 6
3817                     1                   4                 6

[3818 rows x 3 columns]

In [ ]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   str
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   str
dtypes: int64(4), str(9)
memory usage: 387.9 KB

In [ ]:
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

In [ ]:
dados['preco']

0       $110.00
1        $45.00
2        $55.00
3        $52.00
4        $85.00
         ...
3813    $299.00
3814    $199.00
3815    $400.00
3816    $250.00
3817    $350.00
Name: preco, Length: 3818, dtype: str

In [ ]:
dados['preco'] = dados['preco'].apply(lambda x: x.replace('$', '').replace(',', ''))

In [ ]:
dados['preco'] = dados['preco'].astype(np.float64)

In [ ]:
display(dados.head())

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,110.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,45.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,55.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,52.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,85.0

In [ ]:
dados[['taxa_deposito', 'taxa_limpeza']] = dados[['taxa_deposito', 'taxa_limpeza']].map(
    lambda x: float(x.replace('$', '').replace(',', '').strip())
)

In [ ]:
dados[['taxa_deposito', 'taxa_limpeza']].astype(np.float64)

      taxa_deposito  taxa_limpeza
0               0.0           0.0
1               0.0           0.0
2               0.0           0.0
3               0.0          20.0
4               0.0          15.0
...             ...           ...
3813         1000.0         178.0
3814            0.0          99.0
3815            0.0           0.0
3816         1000.0         150.0
3817          500.0           0.0

[3818 rows x 2 columns]

In [ ]:
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [ ]:
dados["descricao_local"] = dados["descricao_local"].str.lower()

dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   str
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(3), int64(4), str(6)
memory usage: 387.9 KB

In [ ]:
dados["descricao_local"]

0       this clean and comfortable one bedroom sits ri...
1       our century old upper queen anne house is loca...
2       cozy room in two-bedroom apartment along the l...
3       very lovely and cozy room for one. convenientl...
4       the “studio at mibbett hollow' is in a beautif...
                              ...
3813    beautiful craftsman home in the historic wedgw...
3814    located in a very easily accessible area of se...
3815    this home is fully furnished and available wee...
3816    this business-themed modern home features:  *h...
3817    this welcoming home is in the quiet residentia...
Name: descricao_local, Length: 3818, dtype: str

In [ ]:
dados["descricao_local"] = dados["descricao_local"].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

dados["descricao_local"] = dados["descricao_local"].str.replace('(?<!\w)-(?!\w)', '', regex=True)

<>:1: SyntaxWarning: "\-" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\-"? A raw string is also an option.
<>:3: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:1: SyntaxWarning: "\-" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\-"? A raw string is also an option.
<>:3: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
/var/folders/_b/dnfcy9r13xvd5mtb_y7ckyd80000gn/T/ipykernel_15398/271151730.py:1: SyntaxWarning: "\-" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\-"? A raw string is also an option.
  dados["descricao_local"] = dados["descricao_local"].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)
/var/folders/_b/dnfcy9r13xvd5mtb_y7ckyd80000gn/T/ipykernel_15398/271151730.py:3: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  dados["descricao_local"] = dados["descricao_local"].str.replace('(?<!\w)-(?!\w)', '', regex=True)

In [ ]:
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,this clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,our century old upper queen anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,very lovely and cozy room for one convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,the studio at mibbett hollow' is in a beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [ ]:
dados["comodidades"] = dados["comodidades"].str.replace('\{|}|\"', "", regex=True)

dados["comodidades"] = dados["comodidades"].str.split(",")

<>:1: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
<>:1: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
/var/folders/_b/dnfcy9r13xvd5mtb_y7ckyd80000gn/T/ipykernel_15398/1104273909.py:1: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
  dados["comodidades"] = dados["comodidades"].str.replace('\{|}|\"', "", regex=True)

In [ ]:
dados["comodidades"]

0       [Internet, Wireless Internet, Kitchen, Free Pa...
1       [TV, Internet, Wireless Internet, Kitchen, Fre...
2       [TV, Internet, Wireless Internet, Kitchen, Fre...
3       [Internet, Wireless Internet, Kitchen, Free Pa...
4       [Wireless Internet, Kitchen, Free Parking on P...
                              ...
3813    [TV, Cable TV, Internet, Wireless Internet, Ai...
3814    [TV, Cable TV, Internet, Wireless Internet, Ki...
3815    [TV, Cable TV, Internet, Wireless Internet, Ai...
3816    [TV, Cable TV, Internet, Wireless Internet, Ai...
3817    [TV, Internet, Wireless Internet, Kitchen, Fre...
Name: comodidades, Length: 3818, dtype: object

In [ ]:
display(dados.head())

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,this clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,110.0
1,10.0,--,1,our century old upper queen anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,45.0
2,10.0,--,1,cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,55.0
3,10.0,--,1,very lovely and cozy room for one convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,20.0,52.0
4,10.0,--,1,the studio at mibbett hollow' is in a beautif...,--,1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,15.0,85.0

In [ ]:
dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.lower()

In [ ]:
dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.replace('\{|}|\"', "", regex=True)

dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.replace('(?<!\w)-(?!\w)', '', regex=True)

<>:1: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
<>:3: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
<>:1: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
<>:3: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
/var/folders/_b/dnfcy9r13xvd5mtb_y7ckyd80000gn/T/ipykernel_15398/1792187328.py:1: SyntaxWarning: "\{" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\{"? A raw string is also an option.
  dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.replace('\{|}|\"', "", regex=True)
/var/folders/_b/dnfcy9r13xvd5mtb_y7ckyd80000gn/T/ipykernel_15398/1792187328.py:3: SyntaxWarning: "\w" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\w"? A raw string is also an option.
  dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.replace('(?<!\w)-(?!\w)', '', regex=True)

In [ ]:
dados["descricao_vizinhanca"] = dados["descricao_vizinhanca"].str.split()

In [ ]:
dados["descricao_vizinhanca"].head()

0    [lower, queen, anne, is, near, the, seattle, c...
1    [upper, queen, anne, is, a, really, pleasant,,...
2    [the, convenience, of, being, in, seattle, but...
3    [ballard, is, lovely,, vibrant, and, one, of, ...
4                                                   []
Name: descricao_vizinhanca, dtype: object

In [20]:
caminho2 = '/Users/samuelmacedo/Downloads/moveis_disponiveis.json'

df = pd.read_json(caminho2)

In [21]:
df

          id        data  vaga_disponivel    preco
0        857  2016-01-04            False      NaN
1        857  2016-01-05            False      NaN
2        857  2016-01-06            False      NaN
3        857  2016-01-07            False      NaN
4        857  2016-01-08            False      NaN
...      ...         ...              ...      ...
364995  3279  2016-12-29             True  $140.00
364996  3279  2016-12-30             True  $140.00
364997  3279  2016-12-31             True  $140.00
364998  3279  2017-01-01             True  $140.00
364999  3279  2017-01-02            False      NaN

[365000 rows x 4 columns]

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  str
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  str
dtypes: bool(1), int64(1), str(2)
memory usage: 11.5 MB

In [23]:
df["data"] = pd.to_datetime(df["data"])

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[us]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  str
dtypes: bool(1), datetime64[us](1), int64(1), str(1)
memory usage: 11.5 MB

In [25]:
df["data"].dt.strftime('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: data, Length: 365000, dtype: str

In [ ]:
df.groupby(df["data"].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64

In [29]:
subset = df.groupby(df["data"].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()

In [30]:
subset

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64