In [1]:
import numpy as np
import pandas as pd

dados = {
    "aluno": ["Ana", "Bruno", "Carla", "Diego", "Eva", "Felipe"],
    "prova1": [8.5, 6.0, 9.2, 4.5, 7.0, 5.5],
    "prova2": [7.0, 6.5, 8.8, 5.0, 7.5, 6.0],
    "prova3": [9.0, 5.5, 9.5, 6.0, 8.0, 4.0],
    "prova4": [8.0, 7.0, 9.0, 5.5, 6.5, 5.0]
}

df = pd.DataFrame(dados)

In [2]:
df["media"] = df[["prova1", "prova2", "prova3", "prova4"]].mean(axis=1)
display(df)

    aluno  prova1  prova2  prova3  prova4  media
0     Ana     8.5     7.0     9.0     8.0  8.125
1   Bruno     6.0     6.5     5.5     7.0  6.250
2   Carla     9.2     8.8     9.5     9.0  9.125
3   Diego     4.5     5.0     6.0     5.5  5.250
4     Eva     7.0     7.5     8.0     6.5  7.250
5  Felipe     5.5     6.0     4.0     5.0  5.125

In [3]:
condicoes = [
    df["media"] >= 7,
    (df["media"] >= 5) & (df["media"] < 7),
]

resultado = [
    "aprovado",
    "recuperacao",
]
df["situacao"] = np.select(
    condicoes,
    resultado,
    default="reprovado"
)
display(df)

    aluno  prova1  prova2  prova3  prova4  media     situacao
0     Ana     8.5     7.0     9.0     8.0  8.125     aprovado
1   Bruno     6.0     6.5     5.5     7.0  6.250  recuperacao
2   Carla     9.2     8.8     9.5     9.0  9.125     aprovado
3   Diego     4.5     5.0     6.0     5.5  5.250  recuperacao
4     Eva     7.0     7.5     8.0     6.5  7.250     aprovado
5  Felipe     5.5     6.0     4.0     5.0  5.125  recuperacao

In [4]:
aprovados = df[
    df["situacao"] == "aprovado"
]

display(aprovados)

   aluno  prova1  prova2  prova3  prova4  media  situacao
0    Ana     8.5     7.0     9.0     8.0  8.125  aprovado
2  Carla     9.2     8.8     9.5     9.0  9.125  aprovado
4    Eva     7.0     7.5     8.0     6.5  7.250  aprovado

In [10]:
maior_media = aprovados["media"].max()
display(maior_media)

np.float64(9.125)