In [1]:
import pandas as pd
import json

In [2]:
caminho = '/Users/samuelmacedo/Downloads/dados.json'

In [3]:
df = pd.read_json(caminho)

In [4]:
df

                                             pessoas
0  {'nome': 'João', 'idade': '25', 'endereco': {'...
1  {'nome': 'Maria', 'idade': 30, 'endereco': {'r...

In [6]:
with open(caminho) as f:
    json_bruto = json.load(f)

In [7]:
json_bruto

{'pessoas': [{'nome': 'João',
   'idade': '25',
   'endereco': {'rua': 'Rua A', 'numero': 123, 'cidade': 'São Paulo'},
   'telefones': ['11 1111-1111', '11 2222-2222']},
  {'nome': 'Maria',
   'idade': 30,
   'endereco': {'rua': '', 'numero': 456, 'cidade': 'Rio de Janeiro'},
   'telefones': ['21 3333-3333']}]}

In [10]:
df_normalizado = pd.json_normalize(json_bruto, record_path=['pessoas'])

In [11]:
df_normalizado

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,João,25,"[11 1111-1111, 11 2222-2222]",Rua A,123,São Paulo
1,Maria,30,[21 3333-3333],,456,Rio de Janeiro

In [12]:
df_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             2 non-null      str
 1   idade            2 non-null      object
 2   telefones        2 non-null      object
 3   endereco.rua     2 non-null      str
 4   endereco.numero  2 non-null      int64
 5   endereco.cidade  2 non-null      str
dtypes: int64(1), object(2), str(3)
memory usage: 228.0+ bytes

In [15]:
df_normalizado['idade'] = df_normalizado["idade"].astype(int)

In [16]:
df_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             2 non-null      str
 1   idade            2 non-null      int64
 2   telefones        2 non-null      object
 3   endereco.rua     2 non-null      str
 4   endereco.numero  2 non-null      int64
 5   endereco.cidade  2 non-null      str
dtypes: int64(2), object(1), str(3)
memory usage: 228.0+ bytes

In [17]:
df_normalizado[df_normalizado["endereco.rua"] != '']

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,João,25,"[11 1111-1111, 11 2222-2222]",Rua A,123,São Paulo

In [18]:
df_filtrado = df_normalizado[df_normalizado["endereco.rua"] != '']