In [5]:
import pandas as pd
import numpy as np
import json

In [2]:
caminho = '/Users/samuelmacedo/Downloads/cursos_cadastrados.json'

In [3]:
df = pd.read_json(caminho)

In [4]:
df

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.9,"{'nome': 'João Silva', 'email': 'joao.silva@em..."
1,Excel para iniciantes,Produtividade,NaN,None,NaN,NaN,NaN,NaN,"{'nome': 'Maria Oliveira', 'email': 'maria.oli..."
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,"{'nome': 'Ana Santos', 'email': 'ana.santos@em..."
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,"{'nome': '', 'email': 'contato@emailaleatorio...."
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,"{'nome': 'John Smith', 'email': '', 'telefone'..."
5,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.9,"{'nome': 'João Silva', 'email': 'joao.silva@em..."

In [6]:
with open(caminho) as f:
    json_bruto = json.load(f)

In [7]:
json_bruto

[{'curso': 'Introdução à programação',
  'categoria': 'Programação',
  'carga_horaria': '20 horas',
  'concluintes': 100,
  'data_inicio': '2022-01-01',
  'data_conclusao': '2022-01-20',
  'descricao': 'Curso introdutório à programação com Python',
  'preco': '99.90',
  'instrutor': {'nome': 'João Silva',
   'email': 'joao.silva@emailaleatorio.com',
   'telefone': '(11) 9999-9999'}},
 {'curso': 'Excel para iniciantes',
  'categoria': 'Produtividade',
  'carga_horaria': None,
  'concluintes': None,
  'data_inicio': None,
  'data_conclusao': None,
  'descricao': None,
  'preco': None,
  'instrutor': {'nome': 'Maria Oliveira',
   'email': 'maria.oliveira@emailaleatorio.com',
   'telefone': '(11) 8888-8888'}},
 {'curso': 'Marketing digital para negócios',
  'categoria': 'Marketing',
  'carga_horaria': '30 horas',
  'concluintes': 75,
  'data_inicio': '2022-03-01',
  'data_conclusao': '2022-03-31',
  'descricao': 'Curso introdutório em marketing',
  'preco': 89.9,
  'instrutor': {'nome': 'Ana Santos',
   'email': 'ana.santos@emailaleatorio.com',
   'telefone': '(11) 7777-7777'}},
 {'curso': 'Inteligência artificial',
  'categoria': 'Programação',
  'carga_horaria': '40 horas',
  'concluintes': '',
  'data_inicio': '2022-04-01',
  'data_conclusao': '',
  'descricao': 'Curso avançado sobre inteligência artificial com Python',
  'preco': 129.9,
  'instrutor': {'nome': '',
   'email': 'contato@emailaleatorio.com',
   'telefone': ''}},
 {'curso': 'Inglês para negócios',
  'categoria': 'Idiomas',
  'carga_horaria': '20 horas',
  'concluintes': 30,
  'data_inicio': '',
  'data_conclusao': '',
  'descricao': 'Curso de inglês para negócios',
  'preco': 69.9,
  'instrutor': {'nome': 'John Smith', 'email': '', 'telefone': ''}},
 {'curso': 'Introdução à programação',
  'categoria': 'Programação',
  'carga_horaria': '20 horas',
  'concluintes': 100,
  'data_inicio': '2022-01-01',
  'data_conclusao': '2022-01-20',
  'descricao': 'Curso introdutório à programação com Python',
  'preco': '99.90',
  'instrutor': {'nome': 'João Silva',
   'email': 'joao.silva@emailaleatorio.com',
   'telefone': '(11) 9999-9999'}}]

In [8]:
df = pd.json_normalize(json_bruto)

In [9]:
df

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
1,Excel para iniciantes,Produtividade,NaN,None,NaN,NaN,NaN,None,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,
5,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999

In [10]:
df.info(
    
)

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               6 non-null      str
 1   categoria           6 non-null      str
 2   carga_horaria       5 non-null      str
 3   concluintes         5 non-null      object
 4   data_inicio         5 non-null      str
 5   data_conclusao      5 non-null      str
 6   descricao           5 non-null      str
 7   preco               5 non-null      object
 8   instrutor.nome      6 non-null      str
 9   instrutor.email     6 non-null      str
 10  instrutor.telefone  6 non-null      str
dtypes: object(2), str(9)
memory usage: 660.0+ bytes

In [12]:
df.isna().sum().sum(
)

np.int64(6)

In [13]:
df.isna().sum()

curso                 0
categoria             0
carga_horaria         1
concluintes           1
data_inicio           1
data_conclusao        1
descricao             1
preco                 1
instrutor.nome        0
instrutor.email       0
instrutor.telefone    0
dtype: int64

In [15]:
df[df.isna().any(axis=1)]

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
1,Excel para iniciantes,Produtividade,NaN,None,NaN,NaN,NaN,None,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888

In [16]:
df.isna().any(axis=1)

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [17]:
df.dropna(inplace=True)

In [19]:
df.duplicated()

0    False
2    False
3    False
4    False
5     True
dtype: bool

In [20]:
df

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,
5,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999

In [21]:
df.drop_duplicates(inplace=True)

In [22]:
df

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,

In [23]:
df[df["instrutor.nome"] == '']

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,

In [24]:
df[df['data_conclusao'] == '']

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,

In [25]:
df.replace('', pd.NA, inplace=True)

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777
3,Inteligência artificial,Programação,40 horas,<NA>,2022-04-01,NaN,Curso avançado sobre inteligência artificial c...,129.9,NaN,contato@emailaleatorio.com,NaN
4,Inglês para negócios,Idiomas,20 horas,30,NaN,NaN,Curso de inglês para negócios,69.9,John Smith,NaN,NaN

In [27]:
df.dropna(inplace=True)

In [28]:
df

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777

In [29]:
df.info()

<class 'pandas.DataFrame'>
Index: 2 entries, 0 to 2
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      str
 1   categoria           2 non-null      str
 2   carga_horaria       2 non-null      str
 3   concluintes         2 non-null      object
 4   data_inicio         2 non-null      str
 5   data_conclusao      2 non-null      str
 6   descricao           2 non-null      str
 7   preco               2 non-null      object
 8   instrutor.nome      2 non-null      str
 9   instrutor.email     2 non-null      str
 10  instrutor.telefone  2 non-null      str
dtypes: object(2), str(9)
memory usage: 192.0+ bytes

In [32]:
df["preco"] = df["preco"].astype(float)

In [33]:
df.info()

<class 'pandas.DataFrame'>
Index: 2 entries, 0 to 2
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      str
 1   categoria           2 non-null      str
 2   carga_horaria       2 non-null      str
 3   concluintes         2 non-null      object
 4   data_inicio         2 non-null      str
 5   data_conclusao      2 non-null      str
 6   descricao           2 non-null      str
 7   preco               2 non-null      float64
 8   instrutor.nome      2 non-null      str
 9   instrutor.email     2 non-null      str
 10  instrutor.telefone  2 non-null      str
dtypes: float64(1), object(1), str(9)
memory usage: 192.0+ bytes

In [34]:
df["concluintes"] = df["concluintes"].astype(int)

In [35]:
df["data_inicio"] = pd.to_datetime(df["data_inicio"])

In [36]:
df["data_conclusao"] = pd.to_datetime(df["data_conclusao"])

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 2 entries, 0 to 2
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      str
 1   categoria           2 non-null      str
 2   carga_horaria       2 non-null      str
 3   concluintes         2 non-null      int64
 4   data_inicio         2 non-null      datetime64[us]
 5   data_conclusao      2 non-null      datetime64[us]
 6   descricao           2 non-null      str
 7   preco               2 non-null      float64
 8   instrutor.nome      2 non-null      str
 9   instrutor.email     2 non-null      str
 10  instrutor.telefone  2 non-null      str
dtypes: datetime64[us](2), float64(1), int64(1), str(7)
memory usage: 192.0 bytes

In [39]:
df.info()

<class 'pandas.DataFrame'>
Index: 2 entries, 0 to 2
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               2 non-null      str
 1   categoria           2 non-null      str
 2   carga_horaria       2 non-null      str
 3   concluintes         2 non-null      int64
 4   data_inicio         2 non-null      datetime64[us]
 5   data_conclusao      2 non-null      datetime64[us]
 6   descricao           2 non-null      str
 7   preco               2 non-null      float64
 8   instrutor.nome      2 non-null      str
 9   instrutor.email     2 non-null      str
 10  instrutor.telefone  2 non-null      str
dtypes: datetime64[us](2), float64(1), int64(1), str(7)
memory usage: 192.0 bytes