In [1]:
import pandas as pd
from pathlib import Path

In [2]:
caminho = '/Users/samuelmacedo/Downloads/dados_vendas_clientes.json'
dados = pd.read_json(caminho)

In [3]:
display(dados)

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [4]:
dados = pd.json_normalize(dados["dados_vendas"])

In [5]:
display(dados)

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [6]:
caminho2 = '/Users/samuelmacedo/Downloads/dados_locacao_imoveis.json'

dados2 = pd.read_json(caminho2)
display(dados2)

                                        dados_locacao
0   {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1   {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2   {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3   {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4   {'apartamento': 'C301 (blocoAP)', 'datas_combi...
5   {'apartamento': 'C302 (blocoAP)', 'datas_combi...
6   {'apartamento': 'D401 (blocoAP)', 'datas_combi...
7   {'apartamento': 'D402 (blocoAP)', 'datas_combi...
8   {'apartamento': 'E501 (blocoAP)', 'datas_combi...
9   {'apartamento': 'E502 (blocoAP)', 'datas_combi...
10  {'apartamento': 'F601 (blocoAP)', 'datas_combi...
11  {'apartamento': 'F602 (blocoAP)', 'datas_combi...
12  {'apartamento': 'G701 (blocoAP)', 'datas_combi...
13  {'apartamento': 'G702 (blocoAP)', 'datas_combi...
14  {'apartamento': 'H801 (blocoAP)', 'datas_combi...

In [8]:
dados2 = pd.json_normalize(dados2["dados_locacao"])

In [9]:
display(dados2)

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [10]:
display(dados.head())

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [11]:
colunas = list(dados.columns)

dados = dados.explode(colunas[1:])

In [12]:
display(dados)

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31
1    07/06/2022  Isabely JOanes 738       R$ 168,07
1    07/06/2022  Isabely JOanes 738       R$ 339,18
1    07/06/2022  Isabely JOanes 738       R$ 314,69
2    08/06/2022  Isabely JOanes 738       R$ 682,05
2    08/06/2022    JOãO Gabriel 671       R$ 386,34
2    08/06/2022  Julya meireles 914       R$ 622,65
2    08/06/2022  Julya meireles 914       R$ 630,79
3    09/06/2022  Julya meireles 914        R$ 390,3
3    09/06/2022     MaRIA Julia 444       R$ 759,16
3    09/06/2022     MaRIA Julia 444       R$ 334,47
3    09/06/2022     MaRIA Julia 444       R$ 678,78
4    10/06/2022     MaRIA Julia 444       R$ 314,24
4    10/06/2022     PEDRO PASCO 812       R$ 311,15
4    10/06/2022    Paulo castro 481       R$ 899,16
4    10/06/2022   Thiago fritzz 883       R$ 885,24

In [13]:
dados.info()

<class 'pandas.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     str
dtypes: str(3)
memory usage: 640.0 bytes

In [18]:
import numpy as np

In [19]:
dados["Valor da compra"] = dados["Valor da compra"].apply(lambda x: x.replace('R$ ', '').replace(',','.'))

dados["Valor da compra"].astype(np.float64)

0    836.50
0    573.33
0    392.80
0    512.34
1    825.31
1    168.07
1    339.18
1    314.69
2    682.05
2    386.34
2    622.65
2    630.79
3    390.30
3    759.16
3    334.47
3    678.78
4    314.24
4    311.15
4    899.16
4    885.24
Name: Valor da compra, dtype: float64

In [20]:
dados.reset_index(drop=True, inplace=True)

In [21]:
display(dados)

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.5
1     06/06/2022  DieGO ARMANDIU 210          573.33
2     06/06/2022  DieGO ARMANDIU 210           392.8
3     06/06/2022  DieGO ARMANDIU 210          512.34
4     07/06/2022  Isabely JOanes 738          825.31
5     07/06/2022  Isabely JOanes 738          168.07
6     07/06/2022  Isabely JOanes 738          339.18
7     07/06/2022  Isabely JOanes 738          314.69
8     08/06/2022  Isabely JOanes 738          682.05
9     08/06/2022    JOãO Gabriel 671          386.34
10    08/06/2022  Julya meireles 914          622.65
11    08/06/2022  Julya meireles 914          630.79
12    09/06/2022  Julya meireles 914           390.3
13    09/06/2022     MaRIA Julia 444          759.16
14    09/06/2022     MaRIA Julia 444          334.47
15    09/06/2022     MaRIA Julia 444          678.78
16    10/06/2022     MaRIA Julia 444          314.24
17    10/06/2022     PEDRO PASCO 812          311.15
18    10/06/2022    Paulo castro 481          899.16
19    10/06/2022   Thiago fritzz 883          885.24

In [22]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     str
dtypes: str(3)
memory usage: 612.0 bytes

In [23]:
display(dados['Valor da compra'].info())

<class 'pandas.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: Valor da compra
Non-Null Count  Dtype
--------------  -----
20 non-null     str
dtypes: str(1)
memory usage: 292.0 bytes

None

In [24]:
dados['Valor da compra'] = dados['Valor da compra'].astype(np.float64)

In [25]:
display(dados.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), str(2)
memory usage: 612.0 bytes

None

In [26]:
dados.head()

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ANA _LUCIA 321           836.50
1    06/06/2022  DieGO ARMANDIU 210           573.33
2    06/06/2022  DieGO ARMANDIU 210           392.80
3    06/06/2022  DieGO ARMANDIU 210           512.34
4    07/06/2022  Isabely JOanes 738           825.31

In [27]:
dados2.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

In [32]:
colunas = list(dados2.columns)
dados2 = dados2.explode(colunas[1:])

dados2.reset_index(drop=True, inplace=True)

In [33]:
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [35]:
dados

   Data de venda             Cliente  Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.50
1     06/06/2022  DieGO ARMANDIU 210           573.33
2     06/06/2022  DieGO ARMANDIU 210           392.80
3     06/06/2022  DieGO ARMANDIU 210           512.34
4     07/06/2022  Isabely JOanes 738           825.31
5     07/06/2022  Isabely JOanes 738           168.07
6     07/06/2022  Isabely JOanes 738           339.18
7     07/06/2022  Isabely JOanes 738           314.69
8     08/06/2022  Isabely JOanes 738           682.05
9     08/06/2022    JOãO Gabriel 671           386.34
10    08/06/2022  Julya meireles 914           622.65
11    08/06/2022  Julya meireles 914           630.79
12    09/06/2022  Julya meireles 914           390.30
13    09/06/2022     MaRIA Julia 444           759.16
14    09/06/2022     MaRIA Julia 444           334.47
15    09/06/2022     MaRIA Julia 444           678.78
16    10/06/2022     MaRIA Julia 444           314.24
17    10/06/2022     PEDRO PASCO 812           311.15
18    10/06/2022    Paulo castro 481           899.16
19    10/06/2022   Thiago fritzz 883           885.24

In [36]:
dados["Cliente"] = dados["Cliente"].str.lower()

In [40]:
dados["Cliente"] = dados["Cliente"].str.replace('[^a-z]', '', regex=True)

In [41]:
dados["Cliente"] = dados["Cliente"].str.replace('[^a-z]', '', regex=True).str.strip()

In [42]:
dados2.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"

In [ ]:
# dados2["apartamento"].str.replace("(blocoAP)", '')

dados2["apartamento"] = dados2["apartamento"].str.replace('\(blocoAP\)', '', regex=True)

<>:3: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
<>:3: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
/var/folders/_b/dnfcy9r13xvd5mtb_y7ckyd80000gn/T/ipykernel_15633/609524640.py:3: SyntaxWarning: "\(" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\("? A raw string is also an option.
  dados2["apartamento"] = dados2["apartamento"].str.replace('\(blocoAP\)', '', regex=True)

In [45]:
dados2

   apartamento datas_combinadas_pagamento datas_de_pagamento   valor_aluguel
0        A101                  01/06/2022         05/06/2022  $ 1000,0 reais
1        A101                  01/07/2022         03/07/2022  $ 2500,0 reais
2        A102                  02/06/2022         02/06/2022  $ 1100,0 reais
3        A102                  02/07/2022         06/07/2022  $ 2600,0 reais
4        B201                  03/06/2022         07/06/2022  $ 1200,0 reais
5        B201                  03/07/2022         03/07/2022  $ 2700,0 reais
6        B202                  04/06/2022         07/06/2022  $ 1300,0 reais
7        B202                  04/07/2022         05/07/2022  $ 2800,0 reais
8        C301                  05/06/2022         10/06/2022  $ 1400,0 reais
9        C301                  05/07/2022         09/07/2022  $ 2900,0 reais
10       C302                  06/06/2022         08/06/2022  $ 1500,0 reais
11       C302                  06/07/2022         12/07/2022  $ 1200,0 reais
12       D401                  07/06/2022         07/06/2022  $ 1600,0 reais
13       D401                  07/07/2022         09/07/2022  $ 1300,0 reais
14       D402                  08/06/2022         10/06/2022  $ 1700,0 reais
15       D402                  08/07/2022         14/07/2022  $ 1400,0 reais
16       E501                  09/06/2022         10/06/2022  $ 1800,0 reais
17       E501                  09/07/2022         09/07/2022  $ 1500,0 reais
18       E502                  10/06/2022         16/06/2022  $ 1900,0 reais
19       E502                  10/07/2022         12/07/2022  $ 1600,0 reais
20       F601                  11/06/2022         17/06/2022  $ 2000,0 reais
21       F601                  11/07/2022         13/07/2022  $ 1000,0 reais
22       F602                  12/06/2022         15/06/2022  $ 2100,0 reais
23       F602                  12/07/2022         12/07/2022  $ 1100,0 reais
24       G701                  13/06/2022         19/06/2022  $ 2200,0 reais
25       G701                  13/07/2022         20/07/2022  $ 1200,0 reais
26       G702                  14/06/2022         15/06/2022  $ 2300,0 reais
27       G702                  14/07/2022         17/07/2022  $ 2100,0 reais
28       H801                  15/06/2022         18/06/2022  $ 2400,0 reais
29       H801                  15/07/2022         16/07/2022  $ 2200,0 reais